const fs = require('fs');
const path = require('path');
const { loadTemplate, renderTemplate } = require('./templates');
const { applyManagedBlock } = require('./utils/managed-block');
const { getPackageVersion } = require('./utils/pkg');

// The 5 journal artifacts rendered into .hydrate/ on scaffold, each paired
// with the console label printed when it's actually created.
const HYDRATE_ARTIFACTS = [
  { name: 'CURRENT_UOW.md', label: 'Created .hydrate/CURRENT_UOW.md (Active Execution Canvas)' },
  { name: 'ROADMAP.md', label: 'Created .hydrate/ROADMAP.md (Tactical Roadmap & Task Index)' },
  { name: 'PROJECT_JOURNAL.md', label: 'Created .hydrate/PROJECT_JOURNAL.md (Decision & Execution Log)' },
  { name: 'DEV_JOURNAL.md', label: 'Created .hydrate/DEV_JOURNAL.md (Lead Developer Journal)' },
  { name: 'ARCHITECT_JOURNAL.md', label: 'Created .hydrate/ARCHITECT_JOURNAL.md (Lead Architect Journal)' }
];

// Zero-touch Claude Code slash commands scaffolded into .claude/commands/ —
// each wraps a `hydrate` CLI verb so a session can boot straight into the
// reconciler, ingest a clipboard UOW, or pull a token-dense context payload
// without the Product Owner typing raw hydrate commands.
const CLAUDE_COMMANDS = [
  { name: 'hydrate.md', label: 'Created .claude/commands/hydrate.md (/hydrate slash command)' },
  { name: 'hydrate-checkup.md', label: 'Created .claude/commands/hydrate-checkup.md (/hydrate-checkup slash command)' },
  { name: 'hydrate-ingest.md', label: 'Created .claude/commands/hydrate-ingest.md (/hydrate-ingest slash command)' },
  { name: 'hydrate-context.md', label: 'Created .claude/commands/hydrate-context.md (/hydrate-context slash command)' },
  { name: 'hydrate-help.md', label: 'Created .claude/commands/hydrate-help.md (/hydrate-help slash command)' },
  { name: 'hydrate-uow.md', label: 'Created .claude/commands/hydrate-uow.md (/hydrate-uow slash command)' },
  { name: 'hydrate-artifacts.md', label: 'Created .claude/commands/hydrate-artifacts.md (/hydrate-artifacts slash command)' },
  { name: 'hydrate-arch-sync.md', label: 'Created .claude/commands/hydrate-arch-sync.md (/hydrate-arch-sync slash command)' },
  { name: 'hydrate-digest.md', label: 'Created .claude/commands/hydrate-digest.md (/hydrate-digest slash command)' },
  { name: 'hydrate-complete.md', label: 'Created .claude/commands/hydrate-complete.md (/hydrate-complete slash command)' },
  { name: 'hydrate-check.md', label: 'Created .claude/commands/hydrate-check.md (/hydrate-check slash command)' },
  { name: 'hydrate-export-portfolio.md', label: 'Created .claude/commands/hydrate-export-portfolio.md (/hydrate-export-portfolio slash command)' },
  { name: 'hydrate-lfg.md', label: 'Created .claude/commands/hydrate-lfg.md (/hydrate-lfg slash command)' }
];

// docs/ artifacts scaffolded alongside .hydrate/ — the architecture map
// (Claude-Code-owned, regenerated by /hydrate-arch-sync) and its narrative
// decision journal (append-only, fed by "Generate Architecture Journal Digest").
const DOCS_ARTIFACTS = [
  { name: 'ARCHITECTURE.md', label: 'Created docs/ARCHITECTURE.md (System Architecture Map)' },
  { name: 'ARCHITECTURE_JOURNAL.md', label: 'Created docs/ARCHITECTURE_JOURNAL.md (Architecture Decision Journal)' }
];

const ACTIVE_COMMAND_NAMES = new Set(CLAUDE_COMMANDS.map((c) => c.name));

// Matches any Hydrate-owned slash command filename, active or not — used to
// scope the deprecated-command purge below so it can never touch a Product
// Owner's own unrelated custom `.claude/commands/*.md` files.
const HYDRATE_COMMAND_NAME_RE = /^hydrate.*\.md$/;

// Deletes any `.claude/commands/hydrate*.md` file that is NOT part of the
// current canonical `CLAUDE_COMMANDS` registry above — e.g. a stray legacy
// `hydrate-architect.md` left over from an older hydrate version
// (UOW-HYDRATE-CLI-DISCOVERABILITY). Runs unconditionally (no `force` gate)
// from both `hydrate init` and `hydrate sync`, since removing genuinely
// orphaned Hydrate-owned files is safe by construction — unlike CLAUDE.md's
// managed block, there's no "customize this file in place" use case a purge
// could clobber. Returns the removed filenames (not full label objects —
// callers format their own report line).
function pruneDeprecatedCommands(cwd) {
  const claudeCommandsDir = path.join(cwd, '.claude', 'commands');
  if (!fs.existsSync(claudeCommandsDir)) return [];

  const removed = [];
  for (const name of fs.readdirSync(claudeCommandsDir)) {
    if (!HYDRATE_COMMAND_NAME_RE.test(name)) continue;
    if (ACTIVE_COMMAND_NAMES.has(name)) continue;
    fs.rmSync(path.join(claudeCommandsDir, name), { force: true });
    removed.push(name);
  }
  return removed;
}

// Idempotently writes just the .claude/commands/ slash-command definitions
// (a subset of scaffold()) from templates/, skipping any file that already
// exists. Used both by `hydrate init`'s full scaffold and by
// bin/postinstall.js, which auto-provisions this into a host project on
// `npm install` without requiring a manual `hydrate init`.
//
// `force: true` (UOW-HYDRATE-15) additionally overwrites any command file
// that already exists but doesn't match the current template render — the
// same "greenfield reset" intent as CLAUDE.md's --force policy, applied to
// the command templates.
function scaffoldClaudeCommands(cwd, { force = false } = {}) {
  const projectName = path.basename(cwd);
  const created = [];

  const claudeCommandsDir = path.join(cwd, '.claude', 'commands');
  if (!fs.existsSync(claudeCommandsDir)) {
    fs.mkdirSync(claudeCommandsDir, { recursive: true });
  }

  for (const { name, label } of CLAUDE_COMMANDS) {
    const filePath = path.join(claudeCommandsDir, name);
    const exists = fs.existsSync(filePath);

    if (!exists) {
      fs.writeFileSync(filePath, renderTemplate(path.join('.claude', 'commands', name), { PROJECT_NAME: projectName }), 'utf8');
      created.push({ path: filePath, label });
      continue;
    }

    if (force) {
      const rendered = renderTemplate(path.join('.claude', 'commands', name), { PROJECT_NAME: projectName });
      if (fs.readFileSync(filePath, 'utf8') !== rendered) {
        fs.writeFileSync(filePath, rendered, 'utf8');
        created.push({ path: filePath, label: label.replace(/^Created/, 'Updated') });
      }
    }
  }

  for (const name of pruneDeprecatedCommands(cwd)) {
    created.push({
      path: path.join(claudeCommandsDir, name),
      label: `Removed deprecated .claude/commands/${name} (not in the current Hydrate command registry)`,
      removed: true
    });
  }

  return created;
}

// Idempotently writes the canonical hydrate scaffold — CLAUDE.md plus the
// 5-artifact .hydrate/ journal layout (and .hydrate/archive/) — from
// templates/, skipping any file that already exists. Returns only the files
// it actually created/updated (plus any guard entries — see below), so
// callers can report exactly what changed instead of re-deriving it from
// disk.
//
// `force: true` (UOW-HYDRATE-15, "Greenfield Harness Reset") wholesale-resets
// CLAUDE.md and the .claude/commands/ templates even when they already carry
// unmanaged legacy content — everything under `.hydrate/` (journals,
// archive, ROADMAP.md, the active canvas) is never touched by `force`
// regardless; it only ever governs the two template surfaces above.
function scaffold(cwd, { force = false } = {}) {
  const projectName = path.basename(cwd);
  const created = [];

  const hydrateDir = path.join(cwd, '.hydrate');
  if (!fs.existsSync(hydrateDir)) {
    fs.mkdirSync(hydrateDir, { recursive: true });
  }

  const archiveDir = path.join(hydrateDir, 'archive');
  if (!fs.existsSync(archiveDir)) {
    fs.mkdirSync(archiveDir, { recursive: true });
  }

  // 1. Operating Rules & AI Execution Protocol, injected as a delimited
  // managed block (UOW-HYDRATE-14 Item 1.1). A brownfield CLAUDE.md (no
  // markers) is left untouched with a guard entry unless `force` is set, in
  // which case it's wholesale-replaced (UOW-HYDRATE-15) — no more silent
  // auto-append into a file the operator never opted into managing.
  const claudePath = path.join(cwd, 'CLAUDE.md');
  const existingClaude = fs.existsSync(claudePath) ? fs.readFileSync(claudePath, 'utf8') : null;
  const claudeBody = renderTemplate('CLAUDE.md', { PROJECT_NAME: projectName });
  const nextClaude = applyManagedBlock(existingClaude, claudeBody, getPackageVersion(), { force });

  if (nextClaude === null) {
    created.push({
      path: claudePath,
      label: "CLAUDE.md has unmanaged content and no Hydrate markers — run 'hydrate init --force' to reset it. Left untouched.",
      guard: true
    });
  } else if (existingClaude !== nextClaude) {
    fs.writeFileSync(claudePath, nextClaude, 'utf8');
    created.push({
      path: claudePath,
      label: existingClaude === null
        ? 'Created CLAUDE.md (Operating Rules & AI Execution Protocol)'
        : force
          ? 'Reset CLAUDE.md (--force: unmanaged legacy content replaced with the managed block)'
          : 'Updated CLAUDE.md (Hydrate Managed Block refreshed)'
    });
  }

  // 2-6. The 5-artifact .hydrate/ journal layout
  for (const { name, label } of HYDRATE_ARTIFACTS) {
    const filePath = path.join(hydrateDir, name);
    if (!fs.existsSync(filePath)) {
      fs.writeFileSync(filePath, renderTemplate(path.join('.hydrate', name), { PROJECT_NAME: projectName }), 'utf8');
      created.push({ path: filePath, label });
    }
  }

  // 7-18. Zero-touch /hydrate-* slash command definitions
  created.push(...scaffoldClaudeCommands(cwd, { force }));

  // 19-20. docs/ architecture map + decision journal
  const docsDir = path.join(cwd, 'docs');
  if (!fs.existsSync(docsDir)) {
    fs.mkdirSync(docsDir, { recursive: true });
  }

  for (const { name, label } of DOCS_ARTIFACTS) {
    const filePath = path.join(docsDir, name);
    if (!fs.existsSync(filePath)) {
      fs.writeFileSync(filePath, renderTemplate(path.join('docs', name), { PROJECT_NAME: projectName }), 'utf8');
      created.push({ path: filePath, label });
    }
  }

  return created;
}

function runInit(options = []) {
  const cwd = process.cwd();
  const force = options.includes('--force') || options.includes('-f');
  const created = scaffold(cwd, { force });

  created.forEach(({ label, guard, removed }) => console.log(`  ${guard ? '⚠' : removed ? '🗑' : '✔'} ${label}`));

  console.log(`
💧 @nemzilla/hydrate Harness Initialized!
=====================================================
1. Review CLAUDE.md and set your exact stack/quality gates.
2. Define your task index & roadmap in .hydrate/ROADMAP.md (Section 1).
3. Run 'hydrate prompt' to lock Claude Code onto the active UOW.
4. Use /hydrate-checkup, /hydrate-ingest, /hydrate-context, /hydrate-help in Claude Code for zero-touch interaction.
`);
}

module.exports = { runInit, scaffold, scaffoldClaudeCommands, pruneDeprecatedCommands, CLAUDE_COMMANDS, HYDRATE_ARTIFACTS, DOCS_ARTIFACTS };
