const fs = require('fs');
const path = require('path');
const { discoverProject } = require('./discover');

const BEGIN_MARKER = '<!-- HYDRATE:BEGIN (auto-generated by `hydrate inject` — safe to edit outside markers) -->';
const END_MARKER = '<!-- HYDRATE:END -->';

function buildHydrateSection(discovery) {
  const commits = discovery.recentCommits.length
    ? discovery.recentCommits.map((c) => `- ${c}`).join('\n')
    : '- No git history detected.';

  return `${BEGIN_MARKER}
## Project Overview
- **Name:** ${discovery.projectName}
- **Primary stack:** ${discovery.stack.join(', ')}
- **Package manager:** ${discovery.packageManager || 'n/a'}
- **Detected directories:** ${discovery.directories.join(', ') || 'n/a'}

## Commands
- **Build:** \`${discovery.buildCommand || 'not detected'}\`
- **Test:** \`${discovery.testCommand || 'not detected'}\`
- **Lint:** \`${discovery.lintCommand || 'not detected'}\`
- **Start/Dev:** \`${discovery.startCommand || 'not detected'}\`

## Recent Activity (git log)
${commits}

## Operational Guardrails
- Focus only on the scope defined in \`.hydrate/CURRENT_UOW.md\` when executing a Unit of Work.
- Do not introduce new frameworks or rewrite unrelated modules without explicit sign-off.
- Run the detected test command above before considering a change complete.
- This section is regenerated by \`hydrate inject\`; edit content outside the markers for anything that should persist across re-runs.
${END_MARKER}`;
}

function writeClaudeMd(cwd, discovery) {
  const claudePath = path.join(cwd, 'CLAUDE.md');
  const section = buildHydrateSection(discovery);

  if (!fs.existsSync(claudePath)) {
    const content = `# CLAUDE.md

This file provides guidance to AI coding agents (Claude Code, etc.) working in this repository.

${section}
`;
    fs.writeFileSync(claudePath, content, 'utf8');
    return { path: claudePath, action: 'created' };
  }

  const existing = fs.readFileSync(claudePath, 'utf8');
  const beginIdx = existing.indexOf(BEGIN_MARKER);
  const endIdx = existing.indexOf(END_MARKER);

  let updated;
  if (beginIdx !== -1 && endIdx !== -1) {
    const before = existing.slice(0, beginIdx);
    const after = existing.slice(endIdx + END_MARKER.length);
    updated = `${before}${section}${after}`;
  } else {
    updated = `${existing.trimEnd()}\n\n${section}\n`;
  }

  fs.writeFileSync(claudePath, updated, 'utf8');
  return { path: claudePath, action: 'updated' };
}

function writeSessionJson(hydrateDir, discovery) {
  const sessionPath = path.join(hydrateDir, 'session.json');

  let existing = null;
  if (fs.existsSync(sessionPath)) {
    try {
      existing = JSON.parse(fs.readFileSync(sessionPath, 'utf8'));
    } catch (err) {
      existing = null;
    }
  }

  const session = {
    version: 1,
    projectName: discovery.projectName,
    stack: discovery.stack,
    packageManager: discovery.packageManager,
    detectedAt: new Date().toISOString(),
    commands: {
      build: discovery.buildCommand,
      test: discovery.testCommand,
      lint: discovery.lintCommand,
      start: discovery.startCommand
    },
    directories: discovery.directories,
    uow: (existing && existing.uow) || { active: null, history: [] },
    featureMemory: (existing && existing.featureMemory) || []
  };

  fs.writeFileSync(sessionPath, `${JSON.stringify(session, null, 2)}\n`, 'utf8');
  return { path: sessionPath, action: existing ? 'updated' : 'created' };
}

function runInject() {
  const cwd = process.cwd();
  const discovery = discoverProject(cwd);

  const hydrateDir = path.join(cwd, '.hydrate');
  if (!fs.existsSync(hydrateDir)) {
    fs.mkdirSync(hydrateDir, { recursive: true });
  }

  const claudeResult = writeClaudeMd(cwd, discovery);
  const sessionResult = writeSessionJson(hydrateDir, discovery);

  console.log(`
💧 @nemzilla/hydrate Injected!
=====================================================
  ✔ ${claudeResult.action === 'created' ? 'Created' : 'Updated'} CLAUDE.md
  ✔ ${sessionResult.action === 'created' ? 'Created' : 'Updated'} .hydrate/session.json

🔎 DISCOVERY SUMMARY
  Project:    ${discovery.projectName}
  Stack:      ${discovery.stack.join(', ')}
  Test:       ${discovery.testCommand || 'not detected'}
  Build:      ${discovery.buildCommand || 'not detected'}
  Lint:       ${discovery.lintCommand || 'not detected'}
  Dirs:       ${discovery.directories.join(', ') || 'n/a'}
  Git log:    ${discovery.recentCommits.length} recent commit(s) scanned

⚡ NEXT STEPS:
   1. Review CLAUDE.md — content outside the HYDRATE markers is yours to edit freely.
   2. Run 'hydrate init' if you also want ROADMAP.md / UOW tracking scaffolding.
   3. Re-run 'hydrate inject' any time to refresh detected stack/commands.
  `);

  return { discovery, claudeResult, sessionResult };
}

module.exports = { runInject, discoverProject, writeClaudeMd, writeSessionJson };
